# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: KY
title: Cyber Security Professional
# email: brett.h@email.co.uk
# website: nobitaky.github.io/yuuzina

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  nobitaky
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
  # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Analytic, people-centric, and with a can-do attitude. Flourish in problem-solving in a fast paced and challenging environment and deliver results within tight schedules. Enhance security resilience in a holistic approach by supporting business decisions, developing cyber security architecture, identifying security gaps, gaining momentum to continuous improvement and inspiring people. Adaptive, flexible, and a team player in cross-functional teams. With a wide variety of experiences in security best practises and tools, and digital transformation.
  
  Eager to meet with people from all walks of life and learn from each other.



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: We built our own SIEM.
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          In 2001, SIEM was not well known in the industry. And those big names like Splunk and Qradar not yet appeared. I, a few of talented consultants, developers and a researcher, we understood the downside of lacking a tool on correlating all the security event. We decided to built our own.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Secure Associates Ltd.
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Regional Security Consultant
        caption: 2001 - 2003
        quote: >
          Secure Associates is a technology start-up offering information security consultancy, managed services and developing own SIEM solution.
        description: | # this will include new lines to allow paragraphs
            We built the blocks. We built the correlation engine based on our everyday experience in threat hunting and incident response. We fine tuned the logic behind one by one manually.
            We won the contract for a HK Gov deploying their first SOC in their backbone. MSSPs in Taiwan, Malaysia and Singapore partnered with us and deployed our tool to help monitoring and protecting their clients.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
