# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: KY
title: Cyber Security Professional
# email: brett.h@email.co.uk
# website: nobitaky.github.io/yuuzina

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  nobitaky
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
  # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Analytic, people-centric, and with a can-do attitude. Flourish in problem-solving in a fast paced and challenging environment and deliver results within tight schedules. Enhance security resilience in a holistic approach by supporting business decisions, developing cyber security architecture, identifying security gaps, gaining momentum to continuous improvement and inspiring people. Adaptive, flexible, and a team player in cross-functional teams. With a wide variety of experiences in security best practises and tools, and digital transformation.
  
  Eager to meet with people from all walks of life and learn from each other.



content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: We built our own SIEM.
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          In 2001, SIEM was not well known in the industry. Those big names like Splunk and Qradar had not yet appeared. I, a researcher, a few of talented consultants and developers, with the understanding of the downside of lacking a tool on correlating all the security events, decided to built our own.

            We built the blocks and the correlation engine of the tool based on our everyday experience in threat hunting and incident response. We fine-tuned the logic behind the tool bit by bit manually.
            
            We won a contract from Govt. for deploying their first SOC. MSSPs in Taiwan, Malaysia and Singapore partnered with us and deployed our tool to monitor and protect their clients.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
